#!/usr/bin/env bash

sudo apt-get -y update
sudo apt-get -y install nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo service nginx start

sudo sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default
sudo sed -i 's/listen \[\:\:\]\:80 default_server;/listen \[\:\:\]\:80;/' /etc/nginx/sites-available/default

sudo service nginx restart

