#!/usr/bin/env bash
# This script ensures Nginx is installed, configured to listen on port 80, and running
sudo apt-get update
sudo apt-get install -y nginx

sudo sed -i 's/listen 80 default_server;/listen 80 default_server;/g' /etc/nginx/sites-available/default
sudo sed -i 's/listen \[::\]:80 default_server;/listen [::]:80 default_server;/g' /etc/nginx/sites-available/default

sudo nginx -t && sudo systemctl restart nginx

sudo ufw allow 80/tcp
