#!/usr/bin/env bash
# Ensures Nginx is running and listening on port 80
apt-get update
apt-get install -y nginx
sed -i 's/listen 80 default_server;/listen 80 default_server;/g' /etc/nginx/sites-available/default
sed -i 's/listen \[::\]:80 default_server;/listen [::]:80 default_server;/g' /etc/nginx/sites-available/default
systemctl restart nginx
