#!/usr/bin/env bash
#print the Best School 10*
counter=0

while [ $counter -lt 10 ]; do
	if [ $counter -eq 8 ]; then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	((counter++))
done
